name: rho_diffusion
channels:
  - intel
  - conda-forge
  - defaults
dependencies:
  - intel::intel-aikit-pytorch=2023.1
  - intel::h5py
  - intel::pip
  - conda-forge::mlflow
  - pip:
    - protobuf==3.20.1
    - '-e ./[dev]'
